### ISSUE TITLE
How can I get model.layers[n].mixer.xai_b?

### ISSUE THREAD

**Issue by DingjieFu** [AmeenAli/HiddenMambaAttn#12]
Hello,

Thank you for your amazing work!

I have a question regarding attention visualization, which is shown in "xai_utils.py". It appears that the Vim model dictionary doesn't have an attribute named 'xai_b'. How can I obtain it?

Thank you!

![1](https://github.com/AmeenAli/HiddenMambaAttn/assets/66894525/d00f05be-3a0a-43db-bbb0-e721cc5dbd44)

**Comment by NKBpower** [comment]
@DingjieFu Hello，how did you solve this problem？I haven't found a solution for this yet, but I noticed that there is this diagram in your work on AAAI, and I would like to know how you solved it?

**Comment by DingjieFu** [comment]
Hi, I've replied to you in our work. The key factor is the version.
