### ISSUE TITLE
cross attention

### ISSUE THREAD

**Issue by zhending111** [AmeenAli/HiddenMambaAttn#13]
Hello, could you tell me how Mamba performs cross-attention operations on images within a batch? I'm not sure if you've researched this area.

**Comment by Itamarzimm** [comment]
Hi @zhending111, 
please refer to item 2 in https://github.com/AmeenAli/HiddenMambaAttn/issues/7#issuecomment-2138932441 and https://github.com/state-spaces/mamba/issues/229

**Comment by zhending111** [comment]
Thanks!!!
