### ISSUE TITLE
About Train Time

### ISSUE THREAD

**Issue by xiequan277** [AmeenAli/HiddenMambaAttn#14]
Thanks sharing your works , it easy to build. but i find it`s so slow when i  want train a model for my datasets with single a GPU，I just guess if changing SSM package? i don`t know.

**Comment by AmeenAli** [comment]
Thanks @xiequan277  for your interest in our work.
Our method does not requiring training, we apply it in a post-hoc manner, we obtain the pre-trained weights from https://github.com/hustvl/Vim . Follow their instructions for more details on training
