### ISSUE TITLE
rollout calculation

### ISSUE THREAD

**Issue by sivaji123256** [AmeenAli/HiddenMambaAttn#4]
Hi @AmeenAli @Itamarzimm ,
I was looking into the code of attention rollout generation. For ViT, start layer is 0 in the ViT roll out code. For Vmamba, you have chosen tart layer as 0, I was trying to understand the reason behind this? I have tried making start layer = 0 , but it was actually printing some random heatmaps. Thanks in advance.

**Comment by AmeenAli** [comment]
Please notice that the number of layers in ViT is 12 and in Mamba-Small is 24. It's a common practice in explanation methods to ignore the first layers, as these layers learn very high-level concepts. In both models, we report the best starting layer for each one separately.
