### ISSUE TITLE
How can I get the "NLP Qualitative Results" in paper?

### ISSUE THREAD

**Issue by AndssY** [AmeenAli/HiddenMambaAttn#8]
Thank you for your interesting and hard work!
But how can I get fig4 "Hidden Attention Matrices" in NLP, or the "NLP Qualitative Results" in paper? Can you provide an example like Explainability Notebook? I want to get similar result in my project.
Thanks again!

**Comment by Itamarzimm** [comment]
Hi @AndssY,

Refer to #7 for details on computing and visualizing the hidden attention matrices of Mamba. 
Regarding experiments in NLP, we plan to add several more examples within the next three weeks. 

Best regards, 
Itamar

**Comment by AndssY** [comment]
Thanks! I have already modified the Jupyter code from Vim to Mamba and got Hidden Attention Matrices.

**Comment by agr505** [comment]
Hi @AndssY , would it be possible to share your modified code? I am also doing research in this area. Thank you

**Comment by AndssY** [comment]
Hi @agr505 , if I remember correctly, I just referred to #7 and set the `cls_pos=L`. You can refer to https://github.com/AndssY/dema/blob/attention/mamba/mamba_ssm/ops/selective_scan_interface.py.
